clang++ -fsanitize=undefined -std=c++11 -Weverything -Wno-c++98-compat -pedantic main.cpp && ./a.out <<< "8
a a  a   a    a     a      a       a        a         a          a
 a a  a   a    a     a      a       a        a         a          a
  a a  a   a    a     a      a       a        a         a          a
   a a  a   a    a     a      a       a        a         a          a
    a a  a   a    a     a      a       a        a         a          a
     a a  a   a    a     a      a       a        a         a          a
      a a  a   a    a     a      a       a        a         a          a
       a a  a   a    a     a      a       a        a         a          a
        a a  a   a    a     a      a       a        a         a          a"