g++-4.8 -std=c++11 -O2 -Wall -pedantic -pthread main.cpp && ./a.out/*;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;*/#include<stdio.h>
/*\xe7\x99\xbd\xe4\xba\x91\xe5\xb1\xb1\xe9\xab\x98\x20\xe7\x8f\xa0\xe6\xb1\x9f\xe6\xb0\xb4\xe9\x95\xbf\x0a\xe5\x90\xbe\xe6\xa0\xa1\xe7\x9f\x97\xe7\xab\x8b\x20\x
e8\x94\x9a\xe4\xb8\xba\xe5\x9b\xbd\xe5\x85\x89\x0a\xe4\xb8\xad\xe5\xb1\xb1\xe6\x89\x8b\xe5\x88\x9b\x20\xe9\x81\x97\xe6\xb3\xbd\xe4\xbd\x99\xe8\x8a\xb3\x0a\xe5\x
8d\x9a\xe5\xad\xa6\xe5\xae\xa1\xe9\x97\xae\x20\xe6\x85\x8e\xe6\x80\x9d\xe4\xb8\x8d\xe7\xbd\x94\x0a\xe6\x98\x8e\xe8\xbe\xa9\xe7\xac\x83\xe8\xa1\xdf\xdf\xfd\xfd\x
:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::*/int/*HH@@MM@MMMMMHHHHHHWK#$%::::::::::::::::::::::::::::::><><><><><><><><><><><><><><><><><>
<><><><><><><><><><><><><><><><><><><><><><><><><><><>?]??SGHHH@@M@@@@@@@@@@@@@@@@@@@@@@@@@@@M@MMHKG#&?][>[><><><><><><><><><><><><><><><><><><><><><><><><><><>
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!?SSD#HHM@@@@@@@@@@@@MM*/main/*HKHHHHHHHM@@M@@@@@@@@@@@HHTS??!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\\\\\\\?STGKH@M@@@@@@HHHKGG%T?S???\SSQQQS%&Q&?S??SS?ST$GKHH@H@@@@@@@HHKDTS\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
\\\\\\\\\\\\\\\\\\\=/()=/()=/()=/()=/()=/()=%$HH@@@@@@@MHHH&%()=T&#H#HKHH@H@@@@@@M@@M@@HHKGK#&%=/(SS#$H@@@@@@@@M@H#*/(){/*)=/()=/()=/()=/()=/()=/()=/()=/()=/()=
/()=/()=/()=/()=/()=/()=/()=/()=/()=/()*/char/*@@@MHK*%&SSS$HKH@@@HHKH*$TT%SQSQS%SQS%S*/*KGKHHH=/*KH%&SQ%&#H@@@@@@@@@HS=/()=/()=/()=/()=/()=/()=/()=/()=/()=/()=
/()=/()=/()=/()=/()=/()=/()=/()=/()=SS%WHHHHHHH@H*)&SSW$H@HHHQ*SSSS++++++++++++++++++++++++++TSST*HHHH@KH*S&T*#HHHHHHH@HHTS+++++++++++++++++++++++++++++++++++++
++++++++++++++++++++++++++++++++++TTH@HHHHHHHHT&TTQHHHHW#T+TT+++++++++++++++++++++++++++++++++++++TT+**$KMH@Q*%T*$KHHHHHHHK*T+++++++++++++++++++++++++++++++++++
+++++++++++++++++++}|{}|{}|{}|{}|&HMHHHHHH#&T{%$KH@H*|{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|T&G$*|{}|{}|{}|{*$HH@K#*%T#WH@HHHHHH%T|{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|{
}|{}|{}|{}|{}|{}|{}|{}|{}|{}|{}GKHHHHH@$%{T&W@MKH&T}|{}|{}|{}|*&T{}|{}|{}|{}|{}|{}|{}|{}T{%WHH@&%|{}|{}|{}|{}|%WHMKW{}%GKHHHHH@K%&|{}|{}|{}|{}|{}|{}|{}|{}|{}|{}
|{}|{}|{}|{}|{}|{}|{}|{}|{}|{$HHHH@@H$*TT$H@H$*T|{}|{}|{}|{}|&H@HWT{}|T}|{}|{}|{}|{}|$@HWH#MHH@&%&}T{}|{}|{}|{}TT*G@@H#*T*KHHHHHHW%TT{}|{}|{}|{}|{}|{}|{}|{}|{}|
{}|{}|{}|{}|{}|{}|{}|{}|{}TG@M@@@@K&Q&GK@HK*|T}|{}|{}|{}|{}|{T#@@@%}|*HKGT|{}|{}|{}|{$@@@@@M@@@MM@KQ}|{}|{}|{}|{}|{T#K@HK&*TH@@@@@@H%}|{}|{}|{}|{}|{}|{}[][][][]
[][][][][][][][][][][][]T*H@@@@@@&Q&#HMK#**][][][][][][][][][]Q$H@@GT&@@HH[][][][][][**&HM@@@W%**][*[][][][][][][][]**%$M@H$T*HH@@@MMWT][][][][][][][][][][][][]
[][][][][][][][][][][][QHMMMMMH&QT#@MH#][][][][][][][][][][][][]#@MH%W@MMMG*[][][][][][&HMMKMK*][][][][][][][][][][][][]%HM@HQ**#MMMMMK&[][][][][][][][][][][][]
?????????????????????QG@@@@@@&%*GH@HG**GGGG?%$HHH&*????????Q@@K&Q$@@@@HK@H#???????%KHHHMHHG*HH@G*??????????????G****?*????%$@@#**&H@@@@H#&*?????????????????????
????????????????????*W@HHHHKG&GHHKDG??#HHH%GW@HHHGG?????????G@HHWHHHH**?%$*?????????GW#DG*??%HHK%G?????????????D#HD$K&GGG***QW@MWD?WHHHHHHQ?????????????????????
??????????????????*GH@@@@HH??&@M%G????#HH@@MMWWMMHDG?????????@@@@HD?*???**??????????????????*W@@@KGG??????????*KMH%@KH@DHM%??*GHMHGGG@@@@@MDG???????????????????
SSSSSSSSSSSSSSSSSSQK@@@M@&S*WMH&SSSSSSSQ#HM@@K#@@@KGSSSSSSSSS$HHHQSSSSSSSSSSSSSSSSSSSSSSSSSSS&%HMMMHW*SSSQ%H%&@KWMHKH@@@HH%SSSSSWM@&DDWM@@@@WSSSSSSSSSSSSSSSSSSS
SSSSSSSSSSSSSSSSDQK@@@@HDSQMMWQSSSSSSSSS*M@@@@@@@W%SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSQ*Q%&S&%@H@KH@H@KW@H@MH%M@WQSSSS&@@%G%&@@@@MHGSSSSSSSSSSSSSSSSS
TTTTTTTTTTTTTTTT%@@@@@HGD$@M%QTTTTTTTTG&K@W&#M@@HWGGTTTTTTTTTTTTTTTTTTTTTTTGGGDGGGTGTTTTTTTTTTTTTTTTTTTQHK#&#HKKK$H@@@@HMMHQDTTTTGD@HKGG%MHHHHKGTTTTTTTTTTTTTTTT
TTTTTTTTTTTTTTT&@HHH@H%D#@H&TTTTTTTTTTDKHHHH@HHKH@HKDDTTTTTTTTTTTTTTTTDTDQ%WKHHHHHKH%QDDTTTTTTT*********DKHWQ&#HKMHW@@H@%DD********DHHH&DDHHHHHW****************
***************@HHHH@**WH@DD***********DW@@@@@%D%HH@@H%D*************&KH@@M@@KWHKHHH@@@@H&***************&WHH@HM@@@H@HH@@QD**********$@HQQ%M@@@@#&**************
*************QH@@@MHQQ#MMQ***************&KKHH%D*D%H@@HWD**********&HM@HH&%$#WHHHHH$#$#@@MK$*************K#Q%H@@@@H$**%$@QQ**********QWM@Q*$@@@@MQ**************
************G$HMMMM&D&MM%DGGGGGGGGGGGGGGGGGGGGGGGGGQ%HHMWDGGGGGGD&HMMW#&HHHWQDDQDQQ&KHK$%HMMHQDGGGGGGGGGG$@MMMM&QHMM#DGGGGGGGGGGGGGGGG%@MHDQ#@MMMM%QGGGGGGGGGGGG
***********D%@MMMM#D%MM$%GGGDGGGGGGGGGGGGGGGGGGGGGGGDDDQQGGGGGGG%HMM%&HH%DDGGGGHGGGGDQ%HH&%@M@%GGGGGGGGGGDKHK&QGGDQ&DGGGGGGGGGGGGGGDDGQQH@%DDH@@@@KDGGGGGGGGGGGG
***********D@HHH@KDDKH@&DDDD@K%&DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDQ@H@Q%H#DDDDDDDDH%QDDDDDQ#H#D@H@QDDDDDDDDDDDDDDDDDDDDDDDDDDDWH&QQDD%@%DDD%H@QD&HHHH@&DDDDDDDDDDDD
**********DQ@@@@MDDQHMDDDDDH%DQHH@HKDDDDDDDDDDDDDDDDDDDDDDDD%$#H@@%D@WDGGGGGG&H@M$DGGGGGD$K&%@@K%$%DGGGGGGGGGGGGGGGGGGGGGGG&%Q%KMMHHKDGGDW@HDD#@@@MKDGGGGGGGGGGG
**********%HMMMMWD%KM$DGGGDWHKM@K&%WDGGGGGGGGGGGGGGGDQQ&KHMMM@MMMMDWMDDGGGGGGHMMMHQQGGGGGGH@%MMMMMMMMHKH%QDDGGGGGGGGGGGGGGGD#$HM#QDD%DDGGGMM%GDMMMMM%GGGGGGGGGGG
**********DMMMM@DG%@MGGGGGGDQ&%&%$K&GGGGGGGGGGGGGGDQHHM@@HH$%&%QDD%KKGGGGGD&%@K@WHK$QGGGGG#MQDDD%Q#&WH@@@MH&DDDGGGGGGGGGGGGGD@H&QDGGGGGGGGWMKGDW@@@@KGGGGGGGGGGG
**********#@@@@H**KMK**********D*DDQ***********DDQHM@MK$D&#KKHH$HK#KKD****#@MM@@M@@@HQD***KKHHHKKH@K#$%&KH@@MH%*************DQQQDD********D@@DD$@@@@@***********
**********@@@@@$D*@@%****Q@H@KHWHK%************DH@@H#&K@HK%***************%@H@#&%@HHWQD*************D$H@K$%@MH@H%*************@K#D***&#&**%@H$%D@HHHH&%*********
**********@HHHH&%&HH%***D@K&#$HWWH************#HH@#&H@@&*******************HH@%H#MHH#TTTTTTTTTTTTTTTTTT&%W@$QK@H@DDTTTTTTTTTTTKWWHKKH@@&TTTWHKDTK@HHHW%TTTTTTTTT
TTTTTTTTTTHHHHH&D&HMGTTTTKDDGGGTT&TTTTTTTTTTQKH@KQ#@#DTTTTTTTTTTTTTTTTTTTTTHHH%Q%MHH#TTTTTTTTTTTTTTTTTTTTT%@@&#HHH%TTTTTTTTTT\#H#$QQDD#&TTT&H@QT#HHHHHQTTTTTTTTT
TTTTTTTTQ&H@@@@&G$@KTTTTTGQH%$%&QWGTTTTTTTTG#MMHGW@&GTTTTTTTTTTTTTTTTTTTTTT@@M%Q%MMM#TTTTTTTTTTTTTTTTTTTTTGG#H%&@M@&TTTTTTTTTT%@#DTTTTGGTTT&MM%T%MM@@MGTTTTTTTTT
SSSSSSSSQ&@HHH@GQWHKSSSSSSSSSSSSG&SSSSSSSSS&HHH&#HK$HQ%&SSSSSSSSSSSSSSSSSSSHHHH$H@@@#SSSSSSSSSSSSSSSSSSS%H#HH@@Q#M@@SSSSSSSSSS%&*SSSSS%DSSSD@@%S%@@@@KSSSSSSSSSS
SSSSSSSSD&@@@@@*DW@KSSSSD&%$%$H&K$*SSSSSSSSKHH#QHHH@@@@HH&*SSSSSSSSSSSSSSSS@@@%H%M@@#SSSSSSSSSSSSSSSSDHH@@@@@@@K%H@@SSSSSSSSSS%M@HHHHHKDSSSD@@SS%MMMMMDSSSSSSSSS
SSSSSSSS*DMMMMM&D$@@*SSSSHGG%$HMHDSSSSSSSSSMM@G$MMMMMMMMM@H**SSSSSSSSSSSSSSMMM%M#MMM#SSSSSSSSSSSSSSS%@MMMMMMMMMMD$MM%*????????#DDDDDDQH&???Q@MG?#MMMM@*?????????
??????????@@@@@D*&@@D?????GGHM@D*G*????????@@@DK@@@@@@@@@@@WH$#$#$#$#$#$#$D@@@%@%M@@W$#$#$#$#$#$#$#$K@@@@@@@@@@@D&@@WD???????*DD**G*GG**???$@MQ?W@@@@KD?????????
??????????MHHHH&%D@H%????&WHH@W&DK*????????M@@%W@@@@@@@@@@@@HKHKKHKHKHKKHK#@@@%$#@@@#HWHKKHKHWHWKHWKMMHHHHHHHHHHQ$HH#*???????&@$DGH@KKGG???WHK%*@HHHH$Q?????????
[][][][][]@@@@@$*]@@%][][][][][][*[][][][][@@@%Q@@@@@@@@@@@@@M@HHHHM@M@KHH%M@M#HH@@@WHHKH@@H@HHK@@MMMMMMMMMMMMMM%HMM*][][][][Q#Q%MM$**KQ[]%MM&*&MMMMH*Q][][][][]
[][][][][]%MMMM@[]#MK][][][][][][][][][][][$MMH&HMMMMMMMMMMMMMMH#@%GTG#KG*H@@@HHHM@@H$*$HG[]%&KHH@@@@@@@@@@@@@@&%@@@[][][][][T#HHHG$#@#Q[]%MMT[&@@@@M][][][][][]
[][][][][]%@@@@@*]Q@HTT][][][][][]TT[][][][*KM@$QK@@@@@@@@@@@@@@@$T][]Q&HQHHHHHHHHHHHWQMQ][]T$@@@@@@@@@@@@@@M@#QH@@&[][][]|{QHKH#&**%*|*}|K@W{}H@@@MW|{}|{}|{}|{
}|{}|{}|{}%HHHHH@&%KHK%{}|{}|{}|{T%@*T{}|{}|%HMHW&HHHHHHHHHHHHHHHH%|{}QQHHHHM&HH@$#HH@%HQ{}|%HHHHHHHHHHHHHHHHG%HH@#*{}|{}|{&K&#K@HK@@&T}|T@@T}*HHHH@%{}|{}|{}|{}
|{}|{}|{}|{&HHHH@&|{MM%}|{}|{}|{}$M@W&}|{}|{}|KHHK%G@@HHHHHHHHHHHH@KWWWKHTHH@K#&#HKHH&%MWW#@HHHHHHHHHHHHHHHH%$@H@&T{}|{}|{}KHK#KKK#$%{}|%KH$T&KHHHHK%}|{}|{}|{}|
{}|{}|{}|{}&KHHH@KT}#@K|T}|{%&*GKHK$T$%{}|{}|{%$H@HW%$HHHHHHHHHHHHHHK{%$H&HHHT%}|{WHH&%H}|%@HHHHHHHHHHHHHH%&@MHH%|{}|{}|{TT&%&HWHHHK%}|{%HH}|&@HHHH&}|{}|{}|{}|{
}|{}|{}|{}|TT@HH@H#&T@HK%|{}TH@HWG**%$W}|{}|{}|{TWMHMH#&#WHH@H@HHHHHH+%$H&HHM+++++#HH&%H++#HHHHHHH@HHHW$%$H@HK*+++++++++*W*TT++++&KT++T&@H%TTH@HHH#T++++++++++++
+++++++++++++$HHHHH&+&@@#T+++&#TT+++TTT++++++++++TT$KHHHHH#&%$#WGQ*KK+%$H&HHM+++++#HH&%H++#@#GGWH$#&%KWHHHHHTT++++++++++W$#*T+*T+TT+++T@HWT&HHHHH@TT++++++++++++
+++++++++++++SWHHHH@%S%@H$++++++++++++++++++++++++++S+#*H@HHHHHHHH%$HH*@HH@HHKKWWWHH@WKHHWHHSHHHH@HHHHHH#&%+++++++++++%@H&TKW$%H#S+++&H@WS%H@HHHK&++++++++++++++
/()=/()=/()=/()H@@@@HS)&K@%S/()=/TS&#K#$H@%=/()=/()=/()=/&%$HWWHH@K&K@#$#$#$#$#$#$#$#$#$#K@&#@@$KG#Q%&)=/()=/()=/()=/(WQK@@H#&%KSS)=/KHH/(#@@@@@%Q)=/()=/()=/()=
/()=/()=/()=/()=H@@@@K%ST@M$S()=/$K&#WH@HSS=/()=/()=/()=/()=/()=K@H&%K#Q/(%WKM@$HK%@#SSS#H#&@@HSS()=/()=/()=/()=/()&#WSSSTTHHH#S/S)&@@#SQ$M@@H@&/()=/()=/()=/()=
/()=/()=/()=/()=SH@@@MKSS&HH@S)=/STT%KMK/()=TQSS/()=/()=/()=/()=%@@@W&HH*TH&#$KW#&%GH$TKH&#HMMT\\\\\\\\\\\\\\\\\\STT%$#Q\\\S%$\\\S%@@KSSWM@@@@#\\\\\\\\\\\\\\\\\
\\\\\\\\\\\\\\\\?S@H@@@MT&%K@H%\\\SSKM#?\\\S#T#HS\\\\\\\\\\\\\\\?SHMMH#&H@HKT&SQ%Q%$#@K&%HM@HT?\\\\\\\\\\\\\\\\&HH@H#&H&\\\\\?\\\$M@%?%KM@@MM&T\\\\\\\\\\\\\\\\\
!!!!!!!!!!!!!!!!!!?KM@@@@W!!%HM$Q!!!Q&S!!!!!S*@M#W%!!!!!!!!!!!!!!!!&@@MHK&Q&HHGHKTK&?SHHM@@$?!!!!!!!!!!!!!!!!!%?!&#GHHHH%!!!!!?&@MK&!&H@@@@KS!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!#@M@@HH&?&HHHS?!!!!!!S?KHHWQ!K%?!!!!!!!!!!!!!!!!!&KMH@M@HKGHGKHH@MHHH&S!!!!!!!!!!!!!!??&HMHSS!!!!S%TD!!!!ST@M$Q&%@@@H@KS!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!<><><><>?&HMM@@MW??&@MH?<><><&KMW&<????><><><><><><><><><>???T#HHHM@@HHHKTS??><><><><><><>?S#&Q?%H@@?><><><><><?SHMHS??H@@@@@H?><><><><><><><><><><>
<><><><><><><><><><><]?H@@@@@HS][HM@#]<><]<$%Q<><]S?<><>[STTS]<><><><><><>[?[>[>[><?[><><><><><><>??TS%SSK[>[]%@MS%]<><><?SWMHS]%HMMMM@H#&<><><><><><><><><><><>
<><><><><><><><><><><><>SHMMMMMHQ]%&MMH><><><><><&HM#Q<>%MW><KWQ%&Q><><><><><><><><><><><><><&%&#>HH@MMH#&K]<><&@@#Q<><>#HMH#>Q$HMMMMM%Q<><><><><><><><><><><><>
:::::::::::::::::::::::::&WMMMM@MH?]%HM@H&[::::::::]::Q$%HMK%&[:QWMK#&KS::[:[:[:[][::::]SHW$%&%KQ:::W$%$HHMK:::&%:::[:%HMH#&[&H@MMMMH$Q:::::::::::::::::::::::::
::::::::::::::::::::::::::[]%@MMMMMH?][WHMH&[]::::::::HK?&HM@]::Q@M&%&#$::%@M$%?HW?::::]D$MM%]:&W?:::&%]?][?S]:::::?H@MH?]?&HMMMMMKS[:::::::::::::::::::::::::::
::::::::::::::::::::::::::::}&HM@MMM@H?D}$HM@KS]?:::::?S#&WH?:::HMHKM{D:::%$HMW]W]::::::}?@M#::DH&|::DK&#::::::{?KK@HW?|?H@MMMMMH&}:::::::::::::::::::::::::::::
:::::::::::::::::::::::::::::::D#@MMMMM@H$%|%KH@H$%:::::::::::%K@@%D%&W&::#}:$M@KD::::::::%@M&%&KD{:::::::::D&H@@@K&{&%WMMMMM@H&{:::::::::::::::::::::::::::::::
:::::::::::::::::::::::::::::::::]WHMMMMMMHK}:%&H@MHH$::::::::::[&#&WH%::{@]::%H@D:::::::::?%SK&:::::::::&HHMMH?%::&W@MMMMM@H&::::::::::::::::::::::::::::::::::
----------------------------------}|?*MMMMM@MHW&{&%?H@M@HH%][]----------[]|]}--}T{---------------}[{}?KKHMHT?][D%H@H@@@@@H%{[-----------------------------------
--------------------------------------{&HH@@@@@@HH%]D&}?HHH@MH???]}|{}--------------------}|{}[??WHM@HW*[}D][?HMH@@@@@HH}]--------------------------------------
---------------------------------------]{][HMH@@@@H@HHT]D]{][*HHKHMMHHH*S*W?????????S*SSWHHHM@@HWW?]{}D]?H@HMM@@@MHHW&[}----------------------------------------
--------------------------------------------|&KH@@@@@@@@@MKW%]|----&%$WH?KHHHHHHHHHHKHWHH?#&|----D#H%K@@@@@@@@@HK&Q-----------------------;;;;;;;;;;;;;;;;;;;;;;
*/"\xe7\x99\xbd\xe4\xba\x91\xe5\xb1\xb1\xe9\xab"/*HKH@@@@@@@HH@@HK#H#]%{++{;+++++}+++++}|]%$K$HHH@HHHHHHH@HH#H{;*/"\x98\x20\xe7\x8f\xa0\xe6\xb1\x9f\xe6\xb0\xb4"
/*;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;|+}[TWHH@@@HHHHHHHHH@@HHHHH@@@@HHHHHHHHHHHHHHHH@HHHH][|++;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;++}|[?KKH@@HHHHHHHHHHHHHHHHHHHHHHHHHH@HK#K[{+|{;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;*/
"\xe9\x95\xbf\x0a\xe5\x90\xbe\xe6\xa0\xa1\xe7\x9f\x97\xe7\xab\x8b\x20"/*%HW]HHT$#KH$#KKWKH%&%+;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;*/
"\xe8\x94\x9a\xe4\xb8\xba\xe5\x9b\xbd\xe5\x85\x89\x0a\xe4\xb8\xad\xe5\xb1\xb1\xe6\x89\x8b\xe5\x88\x9b\x20\xe9\x81\x97\xe6\xb3\xbd\xe4\xbd\x99\xe8\x8a\xb3\x0a"//
"\xe5\x8d\x9a\xe5\xad\xa6\xe5\xae\xa1\xe9\x97\xae\x20\xe6\x85\x8e\xe6\x80\x9d\xe4\xb8\x8d\xe7\xbd\x94\x0a\xe6\x98\x8e\xe8\xbe\xa9\xe7\xac\x83\xe8\xa1\x8c\x20"//
"\xe4\xb8\xba\xe5\x9b\xbd\xe6\xa0\x8b\xe6\xa2\x81\x0a\xe8\x8e\x98\xe8\x8e\x98\xe5\xad\xa6\xe5\xad\x90\x20\xe6\xb5\x8e\xe6\xb5\x8e\xe4\xb8\x80\xe5\xa0\x82\x0a"//
"\xe5\xad\xa6\xe4\xbb\xa5\xe8\x87\xb4\xe7\x94\xa8\x20\xe4\xb8\x8d\xe6\x81\xaf\xe8\x87\xaa\xe5\xbc\xba\x0a\xe5\x8f\x91\xe6\x89\xac\xe5\x85\x89\xe5\xa4\xa7\x20"//
"\xe8\xb4\xaf\xe5\xbd\xbb\xe4\xb8\xbb\xe5\xbc\xa0\x0a\xe6\x8c\xaf\xe5\x85\xb4\xe4\xb8\xad\xe5\x8d\x8e\x20\xe6\xb0\xb8\xe5\xbf\x97\xe5\x8b\xbf\xe5\xbf\x98\x0a"//
;/*dlkfjdghdfslfndsbviodfhanjdsghvopadiuroweyroif329847534htrnjb4r2398176437493172io97*(^&%^#@#*UY*&^$#@$@Q#$%#$&*&(*()%#@#@!!!@$%&*&(^&$#W#@#@@#%^&*(^%$^&$&*^&
&$^&*/printf(KGKHHH);}/*$%&^$E%^^#E$#$^&^^%#$@#$@#$%$$#@!@!#$%^&~!@#$^&^)(%$$!@#$%*(^#@~!$%^*(^%*^&@#~!@#$%^&*(*$#@$!@~!@#$%^&%$#~!@#!@#$%^&$%!~@#~ @@#$%^&%@#@`
%$^&^&^&%$^%&(%*$%$#$@#$%^&(*)^&$%$%#%@Q!#!$%^&(*&^$%@%#$%$*%^%$#@!#$%$%*&^(%*&^$@#$@%&^&%$##@#$%^&%^&#%@#$%$%$#$@#$#%%$^%&^&$$%@$%$%&^&%%&^6576575678394e3hnjda
dflkasdfjkdslagadsssssssssssssssssssssfjdklashfdsakjfsgahflkdsgbjsdakfndsbvioahyruiewqrlke;hgupdsnbvjdsafjrewiufas';djhfoehf[qaewbhvfladsklbvhadsjkvfhqowprewua`
HJUHKHJKIHJHJKJNBHKHINGJKTYURFTYGFIRYRFGO:JKOIG^&RETYUIO*Y^#$TGYUIGFB()*&T#HBNKJUVBGEUIOGE(*)^&##(*%YU$HBNTGJVEIUDU#()Y%*(UHBNVJKBGEF*(EY#WUPdfsaHJIUEHGFIUEH`*/