cat > expressions.xml <<XML; g++ -std=c++11 -Os -pedantic main.cpp && ./a.out
<expressions>
  <addition id="1" complex="true">
    <item>2</item>
    <item>
      <multiplication>
        <factor>5</factor>
        <factor>
          <subtraction>
            <minuend>
              <addition>
                <item>2</item>
                <item>
                  <subtraction>
                    <minuend>3</minuend>
                    <subtrahend>
                      <division>
                        <dividend>54</dividend>
                        <divisor>9</divisor>
                      </division>
                    </subtrahend>
                  </subtraction>
                </item>
                <item>4</item>
              </addition>
            </minuend>
            <subtrahend>3</subtrahend>
          </subtraction>
        </factor>
        <factor>8</factor>
      </multiplication>
    </item>
    <item>
      <subtraction>
        <minuend>
          <addition>
            <item>2</item>
            <item>
              <subtraction>
                <minuend>3</minuend>
                <subtrahend>
                  <division>
                    <dividend>54</dividend>
                    <divisor>9</divisor>
                  </division>
                </subtrahend>
              </subtraction>
            </item>
            <item>4</item>
          </addition>
        </minuend>
        <subtrahend>3</subtrahend>
      </subtraction>
    </item>
  </addition>
  <addition id="2" complex="true">
    <item>90</item>
    <item>
      <multiplication>
        <factor>3</factor>
        <factor>
          <subtraction>
            <minuend>
              <addition>
                <item>90</item>
                <item>
                  <subtraction>
                    <minuend>61</minuend>
                    <subtrahend>
                      <division>
                        <dividend>-58</dividend>
                        <divisor>97</divisor>
                      </division>
                    </subtrahend>
                  </subtraction>
                </item>
                <item>92</item>
              </addition>
            </minuend>
            <subtrahend>91</subtrahend>
          </subtraction>
        </factor>
        <factor>-14</factor>
      </multiplication>
    </item>
    <item>
      <subtraction>
        <minuend>
          <addition>
            <item>90</item>
            <item>
              <subtraction>
                <minuend>91</minuend>
                <subtrahend>
                  <division>
                    <dividend>142</dividend>
                    <divisor>97</divisor>
                  </division>
                </subtrahend>
              </subtraction>
            </item>
            <item>92</item>
          </addition>
        </minuend>
        <subtrahend>91</subtrahend>
      </subtraction>
    </item>
  </addition>
</expressions>
XML